### ISSUE TITLE
Present and Reserved do nothing

### ISSUE THREAD

**Issue by jakerumbles** [jakerumbles/Warehouse_Inventory#17]
We should lock the check boxes on the main inventory page.  You should have to go to the edit modal for each item to edit it.  Also they need to be connected to UPDATE the database.

**Comment by daLoach20** [comment]
Updating is working for other values, but not for Present and Reserved. Need to look into it.

**Comment by daLoach20** [comment]
I did nothing and it's working now. Weird.
